### ISSUE TITLE
techdocs doesn't work with a file named ads.md

### ISSUE THREAD

**Issue by RemonSinnema** [backstage/techdocs-cli#104]
It shows the "someone dropped the mic" error. Renaming it to something else fixes the problem.

Reproduce with [techdocs-issue-with-ads.tar.gz](https://github.com/backstage/techdocs-cli/files/7007602/techdocs-issue-with-ads.tar.gz).

**Comment by emmaindal** [comment]
Hey @RemonSinnema I just tested this myself and do not see the issue you report. Can you try again? Here is what it looks like for me. Please re-open the issue with more details if you still see the issue. 

<img width="374" alt="Screen Shot 2021-08-19 at 11 34 37 AM" src="https://user-images.githubusercontent.com/25153114/130045848-1ebaebff-0e7a-45f0-aa62-66ef69a2a100.png">

<img width="1428" alt="Screen Shot 2021-08-19 at 11 34 03 AM" src="https://user-images.githubusercontent.com/25153114/130046024-16ca43b0-5e42-438e-a730-3fbd5e0c432f.png">

**Comment by RemonSinnema** [comment]
Yes, this issue has been persistent over multiple weeks now. Did you try to click on the `ADS` link? For me, that gives:

![Failure to render ads.md](https://user-images.githubusercontent.com/3496035/130055284-7c5e5b6b-836b-4623-9415-a7abb5be8f7e.png)

BTW, I'm running this with `npx @techdocs/cli serve`.

**Comment by emmaindal** [comment]
@RemonSinnema yes I've been testing it both in one of my own projects and the project you linked above. Please try the latest version `npx @techdocs/cli@0.6.1 serve`.

This is the result of running it with your project (added techdocs-core to plugins in mkdocs.yml) as it is our plugin/extension collection for TechDocs.

 
<img width="1079" alt="Screen Shot 2021-08-19 at 1 16 37 PM" src="https://user-images.githubusercontent.com/25153114/130059904-9f9d18dc-209e-43a5-b0f9-a78708985eb3.png">

**Comment by RemonSinnema** [comment]
The problem persists when explicitly specifying version `0.6.1`.

```
npm version
{
  npm: '7.20.1',
  node: '14.17.0',
  v8: '8.4.371.23-node.63',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
```

**Comment by RemonSinnema** [comment]
Tried with node 16 and got same result.

**Comment by RemonSinnema** [comment]
@emmaindal how do I debug this? Can I see logs somewhere?

**Comment by emmaindal** [comment]
@RemonSinnema hmm interesting, can you try run it with a verbose flag to see if you get any logs that can help us find the issue. Something like `npx @techdocs/cli@0.6.1 serve --verbose`.

**Comment by RemonSinnema** [comment]
Tried that, but not much info:

```shell
npx @techdocs/cli@0.6.1 serve --verbose
info: Starting mkdocs server.
info: Waiting for mkdocs server to start...
verbose: [docker/mkdocs] INFO     -  Building documentation...
verbose: [docker/mkdocs] WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
verbose: [docker/mkdocs] INFO     -  Cleaning site directory
verbose: [docker/mkdocs] INFO     -  Documentation built in 0.37 seconds
verbose: [docker/mkdocs] INFO     -  [13:52:50] Serving on http://0.0.0.0:8000/
info: [techdocs-preview-bundle] Running local version of Backstage at http://localhost:3000
info: Serving docs in Backstage at http://localhost:3000/docs/default/component/local/
Opening browser.
```

**Comment by emmaindal** [comment]
> @emmaindal Tried that, but not much info:
> 
> ```shell
> npx @techdocs/cli@0.6.1 serve --verbose
> info: Starting mkdocs server.
> info: Waiting for mkdocs server to start...
> verbose: [docker/mkdocs] INFO     -  Building documentation...
> verbose: [docker/mkdocs] WARNING  -  Config value: 'dev_addr'. Warning: The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
> verbose: [docker/mkdocs] INFO     -  Cleaning site directory
> verbose: [docker/mkdocs] INFO     -  Documentation built in 0.37 seconds
> verbose: [docker/mkdocs] INFO     -  [13:52:50] Serving on http://0.0.0.0:8000/
> info: [techdocs-preview-bundle] Running local version of Backstage at http://localhost:3000
> info: Serving docs in Backstage at http://localhost:3000/docs/default/component/local/
> Opening browser.
> ```

can you go to http://0.0.0.0:8000/ and see if it works as expected there?

**Comment by RemonSinnema** [comment]
@emmaindal Yes, that works.

**Comment by RemonSinnema** [comment]
@emmaindal I have a similar problem when including an image where the file name starts with `ad-`. Again, renaming it solved the problem.

**Comment by emmaindal** [comment]
Hello @RemonSinnema as it works on the local mkdocs server it seems to be something related to the techdocs app, can you check any logs in the console + network tab?

**Comment by emmaindal** [comment]
Another thing - @RemonSinnema do you have a ad blocker on? can you try to disable that and test without it?

**Comment by RemonSinnema** [comment]
:facepalm: That was it!
