### ISSUE TITLE
Bug when serve with docker on windows

### ISSUE THREAD

**Issue by stephane-mori** [backstage/techdocs-cli#161]
Docker command doesn’t support single quote for argument. It causes an error : 
`docker: Error response from daemon: invalid mode: /content`

This error can be fixed by replacing single quote by double quote at https://github.com/backstage/techdocs-cli/blob/c43800d40dd260af69e5aad87331d178c6039ac0/packages/techdocs-cli/src/lib/mkdocsServer.ts#L39

I can provide a PR for this.

**Comment by stephane-mori** [comment]
https://github.com/backstage/techdocs-cli/pull/162

**Comment by iamEAP** [comment]
Now released and available with `techdocs-cli@v0.8.2`. Thanks again!
