### ISSUE TITLE
Improve npm publish workflow

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/techdocs-cli#21]
As of now, the main workflow in GitHub actions https://github.com/backstage/techdocs-cli/blob/main/.github/workflows/main.yml will try to publish on every PR merge. If the version in `packages/techdocs-cli/package.json` changes, the workflow will pass and a new package will be release.

But this leaves the main build broken all the time. We should improve this behavior.

**Comment by OrkoHunter** [comment]
Preferably, use the GitHub Releases feature to trigger the workflow. It's easier to describe the changelog there and users can subscribe to the releases using GitHub Watch feature.

**Comment by taras** [comment]
Would you be open to using Changesets process that backstage/backstage is using? I created the original proposal in https://github.com/backstage/backstage/issues/1839 and later implemented it in https://github.com/backstage/backstage/pull/2437. It helps to make sure that publishing a release is always one click away. It looks like it could help with releases like https://github.com/backstage/techdocs-cli/issues/25

**Comment by taras** [comment]
BTW, I'm happy to pick up this work if you'd like to do this.

**Comment by OrkoHunter** [comment]
The consistency is good, indeed! +1 from me. (Thanks for introducing us to it - very well remember discussing and thankful for your proposal in early days.)

@hooloovooo and I initially thought it might be an overkill to use changeset for just one package in this project.

**Comment by hooloovooo** [comment]
I don't have too much experience with changesets unfortunately, but since this repo isn't as busy as the main backstage repo our reasoning was that it would be quite easy to keep track of the changes and create a manual changelog IIRC. This might not be the case though, just wanted to clarify our reasoning at the time. :)
+1 for consistency though, it's probably reason enough to introduce Changesets just to keep it familiar to backstage contributors.

**Comment by taras** [comment]
Ok, I'll put it on my TODO list to get all of this setup :)

**Comment by emmaindal** [comment]
Hey @taras just wanted to check in if you still plan to introduce Changesets to this repo or if we should take a look at it? Some of us in the team have been discussing it again to automate the release process as well as get better changelogs.

**Comment by taras** [comment]
Hi @emmaindal, it was and I think it should be done. I got distracted by other things. 

@minkimcello can you please add Changesets to this project?

**Comment by minkimcello** [comment]
@emmaindal ☝️
