### ISSUE TITLE
Investigate if the Backstage mono-repo app can be removed in favor of running techdocs individually

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/techdocs-cli#34]
Ref: https://github.com/backstage/backstage/issues/2707#issuecomment-789875887

techdocs-cli has a Backstage mono-repo in [packages/embedded-techdocs](https://github.com/backstage/techdocs-cli/tree/main/packages/embedded-techdocs) which is used in the [`techdocs-cli serve`](https://github.com/backstage/techdocs-cli/blob/04c0b37b132d1e9c0a50b8929e75e0da9f8c2b9b/packages/techdocs-cli/src/commands/serve/serve.ts#L84-L96) command. Instead of spinning up an entire Backstage app, we could just run a development environment of the TechDocs plugin. This feature was broken until recently for many months; and hence @hooloovooo and I decided to just go ahead with an embedded app.

But the embedded-techdocs way of serving TechDocs comes with a lot of complexity (mono-repo inside a mono-repo, the Backstage packages get outdated quickly, the custom APIs need to be adjusted...). So, investigate if it's possible to spin up just the TechDocs plugin for the `techdocs-cli serve` command, without starting a Backstage app.

**Comment by andrewthauer** [comment]
Potentially fixed by #89

**Comment by andrewthauer** [comment]
I believe this was fixed by #89
