### ISSUE TITLE
serve:mkdocs fails to start when a mkdocs project is located in a directory with spaces

### ISSUE THREAD

**Issue by b-mad** [backstage/techdocs-cli#45]
The following is displayed when the project under use is in a path that contains spaces.

```
verbose: [docker/mkdocs] docker: invalid reference format.
verbose: [docker/mkdocs] See 'docker run --help'.
```

This line does not quote the path for the docker command. https://github.com/backstage/techdocs-cli/blob/main/packages/techdocs-cli/src/lib/mkdocsServer.ts#L36

Add single quotes around the content resolves the issue.

**Comment by OrkoHunter** [comment]
Thanks for reporting and adding suggestion to resolve it!
