### ISSUE TITLE
`techdocs-cli:serve` doesn't display the docs

### ISSUE THREAD

**Issue by dhenneke** [backstage/techdocs-cli#46]
When running `techdocs-cli serve` (or `npx @techdocs/cli`) in the latest version `0.3.4`, the browser only displays a white page with the following errors:

![image](https://user-images.githubusercontent.com/720821/116556539-d9406380-a8fd-11eb-926e-66a46f037d85.png)

Seems like some migrations were not applied to the app after the latest update, but I'm not sure which are missing.

**Comment by iamEAP** [comment]
Thanks for reporting and investigating @dhenneke!  Turns out a simple version bump in this package resolves it.  New version of the CLI forthcoming.
