### ISSUE TITLE
Provide release notes

### ISSUE THREAD

**Issue by Fox32** [backstage/techdocs-cli#63]
Dependabot can't display a lot of details without them.

![image](https://user-images.githubusercontent.com/648527/120171011-da68f700-c201-11eb-8385-f924aeffcdd6.png)

**Comment by emmaindal** [comment]
Hey @Fox32, does dependabot pick up release notes from published releases ([example](https://github.com/backstage/techdocs-cli/releases/tag/v0.6.1)) or do we need to have a changelog.md or something similar?

**Comment by Fox32** [comment]
> Hey @Fox32, does Dependabot pick up release notes from published releases ([example](https://github.com/backstage/techdocs-cli/releases/tag/v0.6.1)) or do we need to have a changelog.md or something similar?
> 

Published releases in GitHub ist sufficient.

**Comment by Fox32** [comment]
But if you have that already than it might be an issue to discover the tags or the repository (e.g. a missing link in package.json)

**Comment by Fox32** [comment]
I'm unable to test it. Can't get dependabot to update to that release right now, not sure why.

**Comment by emmaindal** [comment]
> But if you have that already than it might be an issue to discover the tags or the repository (e.g. a missing link in package.json)

we have just started using it, but I'll add a dependabot yaml for some configuration in the root as I think that is what is missing!

**Comment by emmaindal** [comment]
This should now happen automatically with changesets. Closing this issue and lets see for next release if it actually does, otherwise we can re-open it again!

**Comment by Fox32** [comment]
Doesn't look like this works. I got no release notes for version 0.6.2.

**Comment by Fox32** [comment]
@emmaindal Would like to reopen this, but I don't have a button for it. PRs still look like this:

![image](https://user-images.githubusercontent.com/648527/132214115-810aad81-9a25-4d82-9b39-41db7b405a8c.png)

There are also no release notes (or even git tags) on GitHub available since 6.1. That way it's really hard to understand what is changed between versions.
