### ISSUE TITLE
The 0.6.0 release is missing the --azureAccountKey parameter when publishing

### ISSUE THREAD

**Issue by pschildkamp** [backstage/techdocs-cli#97]
LS,

I've bumped our own pipelines to use the latest and greatest techdocs-cli in order to fix an issue we are facing described here: https://github.com/backstage/backstage/issues/6069#issuecomment-896957514

I updated from `0.3.1` to `0.6.0` and since then my pipelines break because the techdocs-cli does not support the --azureAccountKey parameter anymore. I can't find any documentation whether this is intentional or a bug, by my guess is that this is by accident since the documentation on the trunk still talks still contains this parameter.

To simply reproduce run:
```
npx @techdocs/cli@0.6.0 publish --publisher-type azureBlobStorage --azureAccountName accountName --azureAccountKey key --storage-name container --entity entity
```
This will result in the error: `error: unknown option '--azureAccountKey'`

or 
```
npx @techdocs/cli@0.6.0 publish -h
```

**Comment by aswathysen** [comment]
After the version upgrade I am also facing the same issue. Results in showi error is showing ( **### error: unknown option '--azureAccountKey'**) and not able to proceed with further documentation. The version is showing ### **0.6.0** .

**Comment by pschildkamp** [comment]
@aswathysen, you could consider using version 0.5.0. In that version, the option is still available in that version and worked for me in the meantime.

**Comment by aswathysen** [comment]
@pschildkamp, Okay thanks, will use the version 0.5.0.

**Comment by emmaindal** [comment]
Hey @pschildkamp thank you for reporting this, I do think this is a bug as it still does [exist on the migrate command](https://github.com/backstage/techdocs-cli/blob/main/packages/techdocs-cli/src/commands/index.ts#L70), will check and come back to you!

**Comment by emmaindal** [comment]
This should be back in the next release (next week) @pschildkamp!
